### ISSUE TITLE
COMETS 1.4 Pairwise Analysis Exposure UID

### ISSUE THREAD

**Issue by nateappel** [CBIIT/R-cometsAnalytics#42]
In the pairwise analysis, the exposure_uid and exposure columns are reporting the exposurespec.  Would it be possible to get the actual UID and name in these two columns. 

[pairwise_ouput_sample.xlsx](https://github.com/CBIIT/R-cometsAnalytics/files/1952907/pairwise_ouput_sample.xlsx)

**Comment by steven-moore** [comment]
Hi Dave,

Could you clarify?

S

**Comment by daveruggieri** [comment]
Sure.
Rather than populating the exposure_uid and exposure fields with UIDs and biochemical names, they're currently being populated by "exposure_spec". I think this bug is much easier to visually conceptualize than to read, so I'm attaching an example. I used highlighting to distinguish between "spec" (blue), "UID" (green), and "metabolite name" (yellow). The problem cells are N11:O15, and their expected values are N19:O23.

Let me know if you have questions.
[comets.pairwise.results.exposure.example.xlsx](https://github.com/CBIIT/R-cometsAnalytics/files/2428511/comets.pairwise.results.exposure.example.xlsx)

**Comment by steven-moore** [comment]
Per our phone conversation today, Ella will look into this and issue #22 (the two issues are interrelated)

**Comment by steven-moore** [comment]
The example above was somewhat dated, so I have included a new example based on examining the first three metabolites, in alphabetical order, correlated with one another.  In the screenshot, you can see that the metabolite names were swapped for the "outcomes' but not the "exposures"

![image](https://user-images.githubusercontent.com/34717005/49609750-7172d200-f96a-11e8-86f8-5f2147901b86.png)

In addition, this can also be seen in the download file:

![image](https://user-images.githubusercontent.com/34717005/49609837-b0088c80-f96a-11e8-8758-704053d602b8.png)

**Comment by steven-moore** [comment]
Fixed and closed
